"""Establish the immutable initial schema and audit log table.

Revision ID: 20260902_0001
Revises: None
"""
from alembic import op
import sqlalchemy as sa

revision = "20260902_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('client_ip', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_status_code'), 'audit_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('credential_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_enc', sa.String(length=500), nullable=True),
    sa.Column('enable_password_enc', sa.String(length=500), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_profiles_id'), 'credential_profiles', ['id'], unique=False)
    op.create_table('dc_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dc_sites_id'), 'dc_sites', ['id'], unique=False)
    op.create_index(op.f('ix_dc_sites_name'), 'dc_sites', ['name'], unique=False)
    op.create_table('device_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_device_groups_id'), 'device_groups', ['id'], unique=False)
    op.create_table('ip_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_segment', sa.String(length=100), nullable=True),
    sa.Column('subnet', sa.String(length=100), nullable=True),
    sa.Column('mask', sa.String(length=20), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('usage', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('asset_sn', sa.String(length=100), nullable=True),
    sa.Column('network_type', sa.String(length=20), nullable=True),
    sa.Column('firewall', sa.String(length=100), nullable=True),
    sa.Column('zone_interface_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_inventory_company'), 'ip_inventory', ['company'], unique=False)
    op.create_index(op.f('ix_ip_inventory_device_id'), 'ip_inventory', ['device_id'], unique=False)
    op.create_index(op.f('ix_ip_inventory_id'), 'ip_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_ip_inventory_ip_segment'), 'ip_inventory', ['ip_segment'], unique=False)
    op.create_index(op.f('ix_ip_inventory_sort_order'), 'ip_inventory', ['sort_order'], unique=False)
    op.create_index(op.f('ix_ip_inventory_subnet'), 'ip_inventory', ['subnet'], unique=False)
    op.create_table('ipam_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_added', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_aggregates_id'), 'ipam_aggregates', ['id'], unique=False)
    op.create_index(op.f('ix_ipam_aggregates_name'), 'ipam_aggregates', ['name'], unique=False)
    op.create_index(op.f('ix_ipam_aggregates_prefix'), 'ipam_aggregates', ['prefix'], unique=False)
    op.create_table('schedule_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_configs_id'), 'schedule_configs', ['id'], unique=False)
    op.create_table('server_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_categories_id'), 'server_categories', ['id'], unique=False)
    op.create_index(op.f('ix_server_categories_name'), 'server_categories', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_devices', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('modules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dc_racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('rack_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('width', sa.String(length=20), nullable=True),
    sa.Column('u_height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['dc_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dc_racks_id'), 'dc_racks', ['id'], unique=False)
    op.create_index(op.f('ix_dc_racks_rack_number'), 'dc_racks', ['rack_number'], unique=False)
    op.create_index(op.f('ix_dc_racks_site_id'), 'dc_racks', ['site_id'], unique=False)
    op.create_index(op.f('ix_dc_racks_status'), 'dc_racks', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('credential_profile_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_enc', sa.String(length=500), nullable=True),
    sa.Column('enable_password_enc', sa.String(length=500), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_backup', sa.DateTime(), nullable=True),
    sa.Column('last_discovery', sa.DateTime(), nullable=True),
    sa.Column('last_info_collection', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('production_date_manual', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_profile_id'], ['credential_profiles.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_company'), 'devices', ['company'], unique=False)
    op.create_index(op.f('ix_devices_function'), 'devices', ['function'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    op.create_index(op.f('ix_devices_model'), 'devices', ['model'], unique=False)
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    op.create_table('ipam_prefixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('firewall', sa.String(length=100), nullable=True),
    sa.Column('zone_interface_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_pool', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aggregate_id'], ['ipam_aggregates.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ipam_prefixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_prefixes_aggregate_id'), 'ipam_prefixes', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_ipam_prefixes_id'), 'ipam_prefixes', ['id'], unique=False)
    op.create_index(op.f('ix_ipam_prefixes_parent_id'), 'ipam_prefixes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_ipam_prefixes_prefix'), 'ipam_prefixes', ['prefix'], unique=False)
    op.create_index(op.f('ix_ipam_prefixes_status'), 'ipam_prefixes', ['status'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('linked_device_id', sa.Integer(), nullable=True),
    sa.Column('ad_dn', sa.String(length=500), nullable=True),
    sa.Column('ad_sam', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_category'), 'accounts', ['category'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_table('config_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('config_text', sa.Text(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('backup_time', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('is_changed', sa.Boolean(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('backup_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_backups_config_hash'), 'config_backups', ['config_hash'], unique=False)
    op.create_index(op.f('ix_config_backups_device_id'), 'config_backups', ['device_id'], unique=False)
    op.create_index(op.f('ix_config_backups_id'), 'config_backups', ['id'], unique=False)
    op.create_table('data_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('device_ip', sa.String(length=45), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_logs_category'), 'data_logs', ['category'], unique=False)
    op.create_index(op.f('ix_data_logs_device_id'), 'data_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_data_logs_id'), 'data_logs', ['id'], unique=False)
    op.create_index(op.f('ix_data_logs_timestamp'), 'data_logs', ['timestamp'], unique=False)
    op.create_table('device_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('os_type', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('production_date', sa.String(length=50), nullable=True),
    sa.Column('production_date_source', sa.String(length=20), nullable=True),
    sa.Column('production_date_pattern', sa.String(length=50), nullable=True),
    sa.Column('production_date_raw_match', sa.String(length=500), nullable=True),
    sa.Column('uptime', sa.String(length=200), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('cpu_usage', sa.String(length=50), nullable=True),
    sa.Column('memory_usage', sa.String(length=50), nullable=True),
    sa.Column('interface_up_count', sa.Integer(), nullable=True),
    sa.Column('interface_down_count', sa.Integer(), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('interfaces', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_info_device_id'), 'device_info', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_info_id'), 'device_info', ['id'], unique=False)
    op.create_table('device_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('interface_name', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_ips_device_id'), 'device_ips', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_ips_id'), 'device_ips', ['id'], unique=False)
    op.create_index(op.f('ix_device_ips_ip_address'), 'device_ips', ['ip_address'], unique=False)
    op.create_table('ipam_ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('allocation_type', sa.String(length=10), nullable=True),
    sa.Column('dns_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_device_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('device_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['prefix_id'], ['ipam_prefixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipam_ip_addresses_address'), 'ipam_ip_addresses', ['address'], unique=False)
    op.create_index(op.f('ix_ipam_ip_addresses_allocation_type'), 'ipam_ip_addresses', ['allocation_type'], unique=False)
    op.create_index(op.f('ix_ipam_ip_addresses_assigned_device_id'), 'ipam_ip_addresses', ['assigned_device_id'], unique=False)
    op.create_index(op.f('ix_ipam_ip_addresses_id'), 'ipam_ip_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_ipam_ip_addresses_prefix_id'), 'ipam_ip_addresses', ['prefix_id'], unique=False)
    op.create_index(op.f('ix_ipam_ip_addresses_status'), 'ipam_ip_addresses', ['status'], unique=False)
    op.create_table('it_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('linked_device_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('rack_position', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['dc_racks.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['dc_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_it_assets_asset_type'), 'it_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_it_assets_id'), 'it_assets', ['id'], unique=False)
    op.create_index(op.f('ix_it_assets_linked_device_id'), 'it_assets', ['linked_device_id'], unique=False)
    op.create_index(op.f('ix_it_assets_name'), 'it_assets', ['name'], unique=False)
    op.create_index(op.f('ix_it_assets_rack_id'), 'it_assets', ['rack_id'], unique=False)
    op.create_index(op.f('ix_it_assets_site_id'), 'it_assets', ['site_id'], unique=False)
    op.create_index(op.f('ix_it_assets_status'), 'it_assets', ['status'], unique=False)
    op.create_table('neighbors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('local_interface', sa.String(length=100), nullable=True),
    sa.Column('neighbor_name', sa.String(length=200), nullable=True),
    sa.Column('neighbor_ip', sa.String(length=45), nullable=True),
    sa.Column('neighbor_interface', sa.String(length=100), nullable=True),
    sa.Column('neighbor_platform', sa.String(length=200), nullable=True),
    sa.Column('neighbor_capability', sa.String(length=200), nullable=True),
    sa.Column('neighbor_device_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['neighbor_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighbors_device_id'), 'neighbors', ['device_id'], unique=False)
    op.create_index(op.f('ix_neighbors_id'), 'neighbors', ['id'], unique=False)
    op.create_table('server_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('u_start', sa.Integer(), nullable=True),
    sa.Column('u_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('os', sa.String(length=200), nullable=True),
    sa.Column('cpu', sa.String(length=200), nullable=True),
    sa.Column('memory', sa.String(length=200), nullable=True),
    sa.Column('storage_desc', sa.String(length=300), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['dc_racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_assets_category'), 'server_assets', ['category'], unique=False)
    op.create_index(op.f('ix_server_assets_id'), 'server_assets', ['id'], unique=False)
    op.create_index(op.f('ix_server_assets_name'), 'server_assets', ['name'], unique=False)
    op.create_index(op.f('ix_server_assets_rack_id'), 'server_assets', ['rack_id'], unique=False)
    op.create_index(op.f('ix_server_assets_status'), 'server_assets', ['status'], unique=False)
    op.create_table('server_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_ips_id'), 'server_ips', ['id'], unique=False)
    op.create_index(op.f('ix_server_ips_ip_address'), 'server_ips', ['ip_address'], unique=False)
    op.create_index(op.f('ix_server_ips_server_id'), 'server_ips', ['server_id'], unique=False)
    op.create_table('vm_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('function', sa.String(length=200), nullable=True),
    sa.Column('os_type', sa.String(length=20), nullable=True),
    sa.Column('os_version', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('host_name', sa.String(length=200), nullable=True),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('memory', sa.String(length=100), nullable=True),
    sa.Column('disk_size', sa.String(length=100), nullable=True),
    sa.Column('disk_count', sa.Integer(), nullable=True),
    sa.Column('storage_lun', sa.String(length=500), nullable=True),
    sa.Column('disks', sa.Text(), nullable=True),
    sa.Column('management_ip', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['server_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_instances_function'), 'vm_instances', ['function'], unique=False)
    op.create_index(op.f('ix_vm_instances_host_id'), 'vm_instances', ['host_id'], unique=False)
    op.create_index(op.f('ix_vm_instances_id'), 'vm_instances', ['id'], unique=False)
    op.create_index(op.f('ix_vm_instances_name'), 'vm_instances', ['name'], unique=False)
    op.create_index(op.f('ix_vm_instances_os_type'), 'vm_instances', ['os_type'], unique=False)
    op.create_index(op.f('ix_vm_instances_status'), 'vm_instances', ['status'], unique=False)
    op.create_table('vm_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vm_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_ips_id'), 'vm_ips', ['id'], unique=False)
    op.create_index(op.f('ix_vm_ips_ip_address'), 'vm_ips', ['ip_address'], unique=False)
    op.create_index(op.f('ix_vm_ips_vm_id'), 'vm_ips', ['vm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Removing the baseline would require dropping every application table.
    # Fail explicitly instead of silently clearing alembic_version and leaving
    # the schema in an inconsistent, non-upgradable state.
    raise RuntimeError("Downgrading the initial baseline is intentionally disabled")
